// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat_msg.proto

/*
Package msg is a generated protocol buffer package.

It is generated from these files:
	chat_msg.proto
	game_msg.proto
	msg.proto
	resp_msg.proto

It has these top-level messages:
	ChatMsg
	GameMsg
	Msg
	RespMsg
*/
package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChatMsg struct {
}

func (m *ChatMsg) Reset()                    { *m = ChatMsg{} }
func (m *ChatMsg) String() string            { return proto.CompactTextString(m) }
func (*ChatMsg) ProtoMessage()               {}
func (*ChatMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterType((*ChatMsg)(nil), "msg.ChatMsg")
}

func init() { proto.RegisterFile("chat_msg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 61 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xce, 0x48, 0x2c,
	0x89, 0xcf, 0x2d, 0x4e, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x2d, 0x4e, 0x57,
	0xe2, 0xe4, 0x62, 0x77, 0xce, 0x48, 0x2c, 0xf1, 0x2d, 0x4e, 0x4f, 0x62, 0x03, 0x0b, 0x1b, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x56, 0x2a, 0xd6, 0x70, 0x28, 0x00, 0x00, 0x00,
}
